            var inspectColumn:InspectColumn = InspectColumn()

                inspectColumn = InspectColumn()
                inspectColumn.setCell( Cell( "검사항목" ) )
                inspectColumn.setCell( Cell( "점수" ) )
                inspectColumn.setCell( Cell( "측정값" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "기준값" ) )

                inspectColumn.setCell( Cell( "검사항목" ) )
                inspectColumn.setCell( Cell( "점수" ) )
                inspectColumn.setCell( Cell( "측정값" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "기준값" ) )

                inspectColumn.setCell( Cell( "검사항목" ) )
                inspectColumn.setCell( Cell( "점수" ) )
                inspectColumn.setCell( Cell( "측정값" ) )
                inspectColumn.setCell( Cell( "기준값" ) )
                inspectColumn.setCell( Cell( "" ) )

                inspectColumn.setCell( Cell( "검사항목" ) )
                inspectColumn.setCell( Cell( "측정값" ) )
                inspectColumn.setCell( Cell( "기준값" ) )

            paper.add( inspectColumn )


                inspectColumn.setCell( Cell( "총단백" ) )
                inspectColumn.setCell( Cell( "11" ) )
                inspectColumn.setCell( Cell( "TP" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "6.7~8.3" ) )

                inspectColumn.setCell( Cell( "백혈구수" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "WBC" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "RPR" ) )
                inspectColumn.setCell( Cell( "15" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "92" ) )

                inspectColumn.setCell( Cell( "검사항목" ) )
                inspectColumn.setCell( Cell( "측정값" ) )
                inspectColumn.setCell( Cell( "기준값" ) )
            paper.add( inspectColumn )

                inspectColumn.setCell( Cell( "A/G 비률" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "A/G" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "1.3~2.0" ) )

                inspectColumn.setCell( Cell( "적혈구수" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "RBC" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "TBHA" ) )
                inspectColumn.setCell( Cell( "32" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "" ) )

                inspectColumn.setCell( Cell( "아드레날린" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "60.6~72.0%" ) )
            paper.add( inspectColumn )

                inspectColumn.setCell( Cell( "아르라민" ) )
                inspectColumn.setCell( Cell( "11" ) )
                inspectColumn.setCell( Cell( "ALB" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "3.8~5.3" ) )

                inspectColumn.setCell( Cell( "혈색소량" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "Hb" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "HBS" ) )
                inspectColumn.setCell( Cell( "29" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "" ) )

                inspectColumn.setCell( Cell( "아드레날린" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "1.8~3.2%" ) )
            paper.add( inspectColumn )

                inspectColumn.setCell( Cell( "총비리레빈" ) )
                inspectColumn.setCell( Cell( "11" ) )
                inspectColumn.setCell( Cell( "T-Bil" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "0.20~1.10" ) )

                inspectColumn.setCell( Cell( "헤마또크릿또" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "Ht" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "HCV" ) )
                inspectColumn.setCell( Cell( "120" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "알파" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "5.8~10.2%" ) )
            paper.add( inspectColumn )

                inspectColumn.setCell( Cell( "직접비리레빈" ) )
                inspectColumn.setCell( Cell( "11" ) )
                inspectColumn.setCell( Cell( "D-Bil" ) )
                inspectColumn.setCell( Cell( "0.00~0.40" ) )

                inspectColumn.setCell( Cell( "MCV" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "MCV" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "판정" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "-" ) )
                inspectColumn.setCell( Cell( "91" ) )

                inspectColumn.setCell( Cell( "베타" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "6.9~9.9%" ) )
            paper.add( inspectColumn )

                inspectColumn.setCell( Cell( "직접비리레빈" ) )
                inspectColumn.setCell( Cell( "11" ) )
                inspectColumn.setCell( Cell( "I-Bil" ) )
                inspectColumn.setCell( Cell( "0.20~0.70" ) )

                inspectColumn.setCell( Cell( "MCH" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "MCH" ) )
                inspectColumn.setCell( Cell( "0" ) )
                inspectColumn.setCell( Cell( "M" ) )

                inspectColumn.setCell( Cell( "카토오르" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "0.0" ) )
                inspectColumn.setCell( Cell( "1.0미만" ) )
                inspectColumn.setCell( Cell( "91" ) )

                inspectColumn.setCell( Cell( "감마" ) )
                inspectColumn.setCell( Cell( "" ) )
                inspectColumn.setCell( Cell( "10.1~21.1%" ) )
            paper.add( inspectColumn )

            inspectColumn.setCell( Cell( "TTT" ) )
            inspectColumn.setCell( Cell( "11" ) )
            inspectColumn.setCell( Cell( "TTT" ) )
            inspectColumn.setCell( Cell( "0~5.0" ) )

            inspectColumn.setCell( Cell( "MCHC" ) )
            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "MCHC" ) )
            inspectColumn.setCell( Cell( "0" ) )
            inspectColumn.setCell( Cell( "M" ) )

            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )

            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )
            inspectColumn.setCell( Cell( "" ) )
            paper.add( inspectColumn )